# Etapa 1: build con Maven
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -pl matricula-service -am -DskipTests

# Etapa 2: imagen final, más liviana, solo con el jar
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/matricula-service/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
